## Problema de negócio

Uma grande multinacional varejista do ramo de supermercados deseja ingressar no mercado brasileiro.


Você é o responsável pela análise que servirá de base para a estratégia (tomada de decisão) de entrada dessa empresa no Brasil.

Elabore uma apresentação para os investidores desta empresa buscando realizar as seguintes tarefas: 

Utilizando os dados da ABA Informações_Municipais desse documento:

- Realize uma classificação dos municípios brasileiros com base nas informações disponíveis e faça uma caracterização dos municípios em grupos.

- Elabore uma forma de classificar um novo município entre os grupos já criados na etapa anterior.

- Responda em sua apresentação quais grupos de municípios deveriam ser a porta de entrada para empresa no país e porque.

### Imports

In [1]:
import pandas as pd

### Análise dos Dados

In [2]:
dados = pd.read_excel('..\data\Case Seleção 2021.xls', sheet_name=1, skiprows=3); dados

,Código,Município,Área (km²),"Densidade demográfica, 2000",Distância à capital (km),"Esperança de vida ao nascer, 2000","Mortalidade até um ano de idade, 2000","Taxa de fecundidade total, 2000","Percentual de pessoas de 25 anos ou mais analfabetas, 2000","Renda per Capita, 2000",...,"Taxa de alfabetização, 2000","Média de anos de estudo das pessoas de 25 anos ou mais de idade, 2000","População de 25 anos ou mais de idade, 1991","População de 25 anos ou mais de idade, 2000","População de 65 anos ou mais de idade, 1991","População de 65 anos ou mais de idade, 2000","População total, 1991","População total, 2000","População urbana, 2000","População rural, 2000"
0,520005,Abadia de Goiás (GO),136.9,36.3,21.414308,67.58,27.70,2.85,15.64,205.27,...,88.03,4.87,1872,2433,121,227,4227,4971,3096,1875
1,310010,Abadia dos Dourados (MG),897.4,7.2,390.876513,72.92,20.51,2.54,14.48,196.36,...,86.58,4.36,3308,3781,354,459,6492,6446,3927,2519
2,520010,Abadiânia (GO),1047.7,10.9,78.641435,69.59,22.36,2.77,21.81,168.31,...,82.45,4.24,4241,5918,446,686,9402,11452,7206,4246
3,150010,Abaetetuba (PA),1613.9,73.8,51.184552,70.77,25.61,3.15,24.85,102.14,...,80.74,4.28,33554,44897,3792,4688,99989,119152,70843,48309
4,310020,Abaeté (MG),1822.4,12.3,172.311549,72.50,21.59,2.41,15.56,253.68,...,87.55,4.78,10163,12406,1084,1595,20689,22360,19022,3338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5502,293360,Xique-Xique (BA),5987.5,7.4,517.242182,55.41,83.11,3.84,37.14,73.31,...,70.69,3.16,14678,17840,1950,2450,40373,44718,31565,13153
5503,251740,Zabelê (PB),143.4,12.8,268.334474,60.74,58.40,2.87,42.31,89.61,...,63.05,2.89,816,954,170,170,1728,1853,1186,667
5504,355715,Zacarias (SP),319.7,6.1,447.390579,76.02,8.13,2.21,14.77,195.16,...,86.92,4.82,971,1135,100,152,1961,1947,1332,615
5505,211400,Zé Doca (MA),2044.4,24.1,186.466943,60.02,61.43,3.33,44.67,77.08,...,65.24,2.89,12848,17631,1450,2302,36524,46134,29082,17052
5506,421985,Zortéa (SC),297.8,8.8,296.657231,74.40,14.87,2.50,8.08,211.65,...,92.33,4.86,1005,1310,73,111,2347,2633,2053,580

In [3]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5507 entries, 0 to 5506
Data columns (total 25 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   Código                                                                 5507 non-null   int64
 1   Município                                                              5507 non-null   object
 2   Área (km²)                                                             5507 non-null   float64
 3   Densidade demográfica, 2000                                            5507 non-null   float64
 4   Distância à capital (km)                                               5507 non-null   float64
 5   Esperança de vida ao nascer, 2000                                      5507 non-null   float64
 6   Mortalidade até um ano de idade, 2000                                  5507 non-null   float64
 7   Taxa de fecundidade total, 2000                                        5507 non-null   float64
 8   Percentual de pessoas de 25 anos ou mais analfabetas, 2000             5507 non-null   float64
 9   Renda per Capita, 2000                                                 5507 non-null   float64
 10  Índice de Gini, 2000                                                   5507 non-null   float64
 11  Intensidade da indigência, 2000                                        5507 non-null   float64
 12  Intensidade da pobreza, 2000                                           5507 non-null   float64
 13  Índice de Desenvolvimento Humano Municipal, 2000                       5507 non-null   float64
 14  Taxa bruta de freqüência à escola, 2000                                5507 non-null   float64
 15  Taxa de alfabetização, 2000                                            5507 non-null   float64
 16  Média de anos de estudo das pessoas de 25 anos ou mais de idade, 2000  5507 non-null   float64
 17  População de 25 anos ou mais de idade, 1991                            5507 non-null   int64
 18  População de 25 anos ou mais de idade, 2000                            5507 non-null   int64
 19  População de 65 anos ou mais de idade, 1991                            5507 non-null   int64
 20  População de 65 anos ou mais de idade, 2000                            5507 non-null   int64
 21  População total, 1991                                                  5507 non-null   int64
 22  População total, 2000                                                  5507 non-null   int64
 23  População urbana, 2000                                                 5507 non-null   int64
 24  População rural, 2000                                                  5507 non-null   int64
dtypes: float64(15), int64(9), object(1)
memory usage: 1.1+ MB